# Website settings
baseurl: "/"
url: "http://vm.thekkedam.org"

# Internal nav
nav:
  main:
    home: "/"
    profile: "/profile"
    projects: "/projects"
    posts: "/writing"
# TODO
#    speaking: "/speaking"
    photos: "/photos"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Vipin Madhavanunni"
slogan: "Programmer, traveler, Hiker and dreamer"
description: "The home page of Vipin Madhavanunni."
thumbnail_path: "vipintm-medium.jpg"
bitcoin_address: "1DyKgHsw6uwxGq3apy4mwqG6DtCayj4bfm"
unws_startup_url: "http://www.unwsolution.com/"
website_repo_url: "https://github.com/thekkedam/vm.thekkedam.org"
olt_url: "http://www.onceinlifetime.com/"
embedur_url: "http://embedur.com/"
aukbc_url: "http://www.au-kbc.org/comm/"

# Profile
resume_path: "https://www.sharelatex.com/github/repos/vipintm/cv/builds/latest/output.pdf"
resume_src: "https://github.com/vipintm/cv"

# URLs
contact_urls:  
  twitter: 
    url: "https://twitter.com/vipintm"
    label: "Twitter"
    icon: "twitter-square"
    username: "@vipintm"
  linkedin: 
    url: "https://www.linkedin.com/in/vipintm"
    label: "LinkedIn"
    icon: "linkedin-square"
  xing:
    url: "https://www.xing.com/profile/Vipin_Madhavanunni"
    label: "Xing"
    icon: "xing-square"
  facebook: 
    url: "https://www.facebook.com/vipintm"
    label: "Facebook"
    icon: "facebook-square"
  google: 
    url: "https://plus.google.com/+VipinM/"
    label: "Google+"
    icon: "google-plus-square"
  github: 
    url: "https://github.com/vipintm/"
    label: "GitHub"
    icon: "github-square"
  email: 
    url: "mailto:vipmadha@gmail.com"
    label: "Email"
    value: "vipmadha@gmail.com"
    icon: "envelope-square"
  inum:
    url: "tel:+883510001197378"
    label: "Inum"
    icon: "phone-square"
  keybase:
    url: "https://keybase.io/vipintm"
    label: "Keybase"
    icon: "user-secret"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title"
sass:
  sass_dir: "/assets/css"
  style: :compressed  
highlighter: pygments
timezone: 'Europe/Berlin'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
