# Website settings
baseurl: "/"
url: "http://vm.thekkedam.org"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
    projects: "/projects"
    photos: "/photos"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Vipin Madhavanunni"
slogan: "Programmer, traveler, Hiker, dreamer"
description: "The home page of Vipin Madhavanunni, and software engineer."
thumbnail_path: "vipintm-medium.jpg"
bitcoin_address: "1PntwKCSQahUzr7KThduA59R1QW8B3zrAz"
unws_startup_url: "http://www.unwsolution.com/"
website_repo_url: "https://github.com/thekkedam/vm.thekkedam.org"
olt_url: "http://www.onceinlifetime.com/"
embedur_url: "http://embedur.com/"
aukbc_url: "http://www.au-kbc.org/comm/"

# URLs
contact_urls:  
  twitter: 
    url: "https://twitter.com/vipintm"
    label: "Twitter"
    icon: "twitter-square"
    username: "@vipintm"
  linkedin: 
    url: "https://www.linkedin.com/in/vipintm"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook: 
    url: "https://www.facebook.com/vipintm"
    label: "Facebook"
    icon: "facebook-square"
  google: 
    url: "https://plus.google.com/+VipinM/"
    label: "Google+"
    icon: "google-plus-square"
  slideshare: 
    url: "https://www.slideshare.net/vipintm"
    label: "SlideShare"
    icon: "slideshare"
  github: 
    url: "https://github.com/vipintm/"
    label: "GitHub"
    icon: "github-square"
  email: 
    url: "mailto:vipintm@gmail.com"
    label: "Email"
    value: "vipintm@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title"
sass:
  sass_dir: "/assets/css"
  style: :compressed  
highlighter: pygments
timezone: 'Europe/Berlin'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
