#!/bin/bash

WORKSPACE=$(pwd)
COMMIT_TIME=$(date +"%m-%d-%Y-%H:%M")
COMMIT_MSG="Updated-$COMMIT_TIME"

is_git=0

if [ -f _scripts/bash_func ]; then
	. _scripts/bash_func
else
	echo "Error on _scripts/bash_func ..."
fi


### MAIN ###
check_git

clean_old_logs
get_version

gem_update
site_build
make_diploy

clean_old_logs
check_new
git_commit
git_push
clean_old_logs
