source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('./versions.json').read)

gem 'github-pages'
gem 'pygments.rb'
gem 'jekyll-mentions'
gem 'jekyll-sitemap'
gem 'jekyll-gist'
gem 'jekyll-paginate'
gem 'html-proofer'

