source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('./versions.json').read)

gem 'github-pages', '>= 214', versions['github-pages'], group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem 'rouge', versions['rouge']
  gem 'jekyll-mentions', '>= 1.5.1', versions['jekyll-mentions']
  gem 'jekyll-sitemap', '>= 1.4.0', versions['jekyll-sitemap']
  gem 'jekyll-gist', '>= 1.5.0', versions['jekyll-gist']
  gem 'jekyll-paginate', versions['jekyll-paginate']
  gem 'html-proofer', '>= 3.15.3'
end
